CREATE USER sisadmin WITH SUPERUSER PASSWORD 's1sadm1n';
CREATE USER dart WITH SUPERUSER PASSWORD 'dart';
CREATE DATABASE dart_test;
GRANT ALL PRIVILEGES ON DATABASE dart_test TO dart;
ALTER USER postgres with PASSWORD 'dart';
ALTER USER dart with PASSWORD 'dart';